/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokyo;

import javax.swing.ImageIcon;

/**
 *
 * @author Orlandi
 */
public class Modalidade extends javax.swing.JFrame {

    /**
     * Creates new form Modalidade
     */
    public Modalidade() {
        initComponents();
        this.setTitle("Tokyo++ - Modalidade");
        this.setIconImage(new ImageIcon(getClass().getResource("/img/japan.png")).getImage()); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonListar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        Inseributtonr = new javax.swing.JButton();
        buttonAtualizar = new javax.swing.JButton();
        paneModalidade = new javax.swing.JScrollPane();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelNome1 = new javax.swing.JLabel();
        textFieldCategoria = new javax.swing.JTextField();
        labelNome2 = new javax.swing.JLabel();
        labelNome3 = new javax.swing.JLabel();
        textFieldMax = new javax.swing.JTextField();
        paneEsporte = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonListar.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        buttonListar.setText("Listar");
        buttonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarActionPerformed(evt);
            }
        });

        buttonRemover.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        buttonRemover.setText("Remover");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        Inseributtonr.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        Inseributtonr.setText("Inserir");
        Inseributtonr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InseributtonrActionPerformed(evt);
            }
        });

        buttonAtualizar.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        buttonAtualizar.setText("Atualizar");
        buttonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarActionPerformed(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelNome.setText("Nome da modalidade:");

        textFieldNome.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        textFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeActionPerformed(evt);
            }
        });

        labelNome1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelNome1.setText("Número máximo de atletas:");

        textFieldCategoria.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        textFieldCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCategoriaActionPerformed(evt);
            }
        });

        labelNome2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelNome2.setText("Categoria:");

        labelNome3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        labelNome3.setText("Esporte:");

        textFieldMax.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        textFieldMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNome)
                            .addComponent(textFieldCategoria)
                            .addComponent(textFieldMax)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNome)
                                    .addComponent(labelNome3)
                                    .addComponent(labelNome2)
                                    .addComponent(labelNome1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(paneEsporte)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inseributtonr, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNome1)
                        .addGap(11, 11, 11)
                        .addComponent(textFieldMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNome2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNome3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paneEsporte, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(paneModalidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonListar)
                    .addComponent(buttonRemover)
                    .addComponent(Inseributtonr)
                    .addComponent(buttonAtualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRemoverActionPerformed

    private void buttonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonListarActionPerformed

    private void InseributtonrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InseributtonrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InseributtonrActionPerformed

    private void buttonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAtualizarActionPerformed

    private void textFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeActionPerformed

    private void textFieldCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCategoriaActionPerformed

    private void textFieldMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMaxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inseributtonr;
    private javax.swing.JButton buttonAtualizar;
    private javax.swing.JButton buttonListar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JLabel labelNome2;
    private javax.swing.JLabel labelNome3;
    private javax.swing.JScrollPane paneEsporte;
    private javax.swing.JScrollPane paneModalidade;
    private javax.swing.JTextField textFieldCategoria;
    private javax.swing.JTextField textFieldMax;
    private javax.swing.JTextField textFieldNome;
    // End of variables declaration//GEN-END:variables
}
